services:
  - type: web
    name: dada-api
    env: docker
    dockerContext: backend
    envVars:
      - key: APP_NAME
        value: "Digital Dada"
      - key: OPENAI_API_KEY
        value: replace_me

  - type: web
    name: dada-web
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: build
