version: 1
services:
  - type: web
    name: digital-dada-api-v1
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: digital-dada-web-v1
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishDir: build
